server:
  port: 8081


#数据库链接 改成本地的
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/dadawang?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

#指定mapper.xml的位置
mybatis:
  mapper-locations: classpath:mapper/*.xml